### PR TITLE
[CTFE] Add Metadata field to config

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
The field allows attaching implementation-specific data to the config.

### CODE REVIEW

**Comment by Martin2112** [comment]
What's the intended use for this? And would a proto extension be a suitable alternative?

**Comment by pavelkalinnikov** [comment]
Good point. This belongs to Migrillian :)

**Comment by pavelkalinnikov** [comment]
The intended use there is to have transport configured differently depending on the log operator.

**Comment by Martin2112** [comment]
That might be something that's not needed by the open source code though I can't say that for certain.

**Pull request closed without merging**
