### PR TITLE
Fork updates from Go 1.14

### PR DESCRIPTION
**Pull request by daviddrysdale**
### Checklist

- [x] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
One thing that's worth explicitly flagging: this includes [upstream commit 14521198679e](https://github.com/golang/go/commit/14521198679e), which removes the Entrust.net special case.  So anything that chains to that (now-expired) root will no longer validate.

**Comment by RJPercival** [comment]
I guess that could negatively affect CT logs like Daedalus, which accept expired certs. Might be best to strip out that commit?

**Comment by daviddrysdale** [comment]
Reverted that upstream change

**Comment by RJPercival** [comment]
Could you document in the CHANGELOG that this commit was excluded please?

**Comment by daviddrysdale** [comment]
CHANGELOG updated.

**Comment by AlCutter** [comment]
Thanks, David!

**Comment by daviddrysdale** [comment]
BTW Go 1.15 is incoming and looks to have *lots* of changes in `asn1` and `x509`&hellip;

**Pull request merged**
