### PR TITLE
Don't validate EKU nesting on submissions

### PR DESCRIPTION
**Pull request by daviddrysdale**
For discussion, cf. #197

### CODE REVIEW

**Comment by FiloSottile** [comment]
I would suggest going even further, removing all EKU, name constraints, pathlen, and `subject == parent` (NameMismatch) checks. I think the only things you are likely to care about are `Expired` and of course `NotAuthorizedToSign`.

**Comment by rolandshoemaker** [comment]
I had a similar thought to what @FiloSottile suggests, mainly that we should just disable all of the sanity checking in `Certificate.isValid` and let the chain be built purely by matching certs: https://github.com/google/certificate-transparency-go/compare/master...rolandshoemaker:build-lax-chain.

**Comment by rolandshoemaker** [comment]
(One side note: if we do want to just neuter `Certificate.isValid` the EKU and expiration checks will need to be moved outside of `Certificate.Verify` so logs can control what types of certificates they want to accept.)

**Comment by daviddrysdale** [comment]
PTAL - shifted to allow granular control of various `cert.Verify` checks, and turned most of them off in the CT personality cert checker.

**Pull request merged**
