### PR TITLE
Add Pool of executors

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
This change introduces a Pool type which can be used to run arbitrary
Jobs in a set of parallel executors.

Pool provides two types of clients:
- Client is a thin client which can submit Jobs to the Pool efficiently.
- SyncClient is a Client wrapper that adds support for in-flight Jobs
  limiting, and allows to wait for Jobs termination.

This change also adds usage of the new Pool type in Fetcher/Scanner
and Migrillian. This change is necessary to support multi-tenancy in
Migrillian: it requires multiple Controlllers/Fetchers share the same pool
of workers.

This code will likely migrate to Trillian, as it has a similar use-case: a
multi-tenant setup over a set of shared database workers.

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
PTAL. Probably it's easier to review commit by commit.

**Comment by pavelkalinnikov** [comment]
ping

**Comment by daviddrysdale** [comment]
This seems like a significant change to the internal design of the scanner code, and involves a new paradigm for scheduling work that hides/obscures the normal details of goroutines and channels.  We probably need a higher level discussion before getting to code details.

**Comment by pavelkalinnikov** [comment]
For more context on why I am doing this see [this](https://github.com/pavelkalinnikov/certificate-transparency-go/commit/efbc2299dde07d2462a28bf0855f0b8c9d1331b6) commit: basically in multi-tenant mode Migrillian has a shared pool of workers (in a `Runtime` object), which is used by all migration instances (internally it boils down to all `Fetcher` instances).

**Comment by AlCutter** [comment]
Some higher level questions/thoughts:
* What do you think about the trade-off between increased code complexity enabling a single instance of Migrillian working to migrate multiple logs, vs. simpler code and running a separate instance of Migrillian for each log in the process of being migrated?
* Do you envisage a large number of multiple log migrations happening concurrently?
* Is this multi-tenant migration/copy code shared with the mirror personality?
* What do you think about the same trade-offs mentioned above in that context?

**Comment by pavelkalinnikov** [comment]
Closing as this seems an overkill.

**Pull request closed without merging**
