### PR TITLE
Logs with unknown status not filtered out by SelectByStatus

### PR DESCRIPTION
**Pull request by Mercurrent**

### CODE REVIEW

**Comment by Mercurrent** [comment]
PTAL

**Comment by RJPercival** [comment]
Why do we want SelectByStatus to return logs with no status?

**Comment by Mercurrent** [comment]
We want to filter out only Logs within particular state. For some Logs we have no info (mostly testing). That's heuristic, but we likely to prefer not to filter out those Logs. Not to miss them from potential pool.

**Comment by RJPercival** [comment]
I think this would be surprising behaviour, especially undocumented. Would it not be better to have a method that explicitly selects logs with no state?

**Comment by Mercurrent** [comment]
Ok. Then transition PR is a bit bigger (as testdata updates needed). Deleting this one.

**Pull request closed without merging**
