### PR TITLE
Build the ctfe/ct_server binary without depending on glibc

### LINKED ISSUE #1118: CTFE GLIBC Error
I'm trying the [Docker deployment](https://github.com/google/certificate-transparency-go/tree/master/trillian/examples/deployment/docker/ctfe) on a Amazon Linux server. When I run docker-compose --profile frontend up, it successfully launches the ctfe-db, ctfe-trillian-log-server-1, and ctfe-trillian-log-signer-1 containers. But, I keep getting 'exited with code 1' when it tries to launch the ctfe-ctfe-1 container:

ctfe-ctfe-1                 | /ct_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /ct_server)
ctfe-ctfe-1                 | /ct_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /ct_server)

Any ideas how to get past this error?

### PR DESCRIPTION
**Pull request by roger2hk**
Fixes #1118.

Here is the distroless Dockerfile example for Go.
https://github.com/GoogleContainerTools/distroless/blob/main/examples/go/Dockerfile

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Review by mhutchinson — APPROVED** [review]
Nice one. May be that we also need to do the same for trillian too?

**Comment by roger2hk** [comment]
> Nice one. May be that we also need to do the same for trillian too?

Sure, let me get them fixed after merging this one. The CI `certificate-transparency-go-cloud-build-pull-request (trillian-opensource-ci)` is broken... 😕

**Comment by roger2hk** [comment]
According to https://github.com/GoogleContainerTools/distroless/issues/1342, updating the `CGO_ENABLED` is not appropriate to resolve the issue. The gcr.io/distroless/base Docker image is supposed to include glibc.

**Pull request merged**
