### PR TITLE
Switch from glog to klog

### PR DESCRIPTION
**Pull request by jdolitsky**
Please see the following explanation of the reasons for klog vs. glog: https://github.com/kubernetes/klog#why-was-klog-created

### CODE REVIEW

**Comment by jdolitsky** [comment]
This should pull in latest trillian once this is merged: https://github.com/google/trillian/pull/2787

**Review by AlCutter — APPROVED** [review]
@zkpjedi Would you mind reviewing my two tiny extra commits on Josh's PR?

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
Not that mine counts for anything, lgtm :)

**Review by zkpjedi — APPROVED** [review]

**Comment by JasonGitHub** [comment]
Thanks Al!

**Comment by zkpjedi** [comment]
Thanks Al!

**Pull request merged**
