### PR TITLE
Add missing tools dependencies.

### PR DESCRIPTION
**Pull request by pphaneuf**
### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Review by mhutchinson — APPROVED** [review]

**Comment by mhutchinson** [comment]
The idea is sound. There are lots of errors about missing entries in the go.sum file though?

**Comment by pphaneuf** [comment]
Yeah, this is needing a bit more tweaking, stand by...

**Comment by pphaneuf** [comment]
Alright, seems happier now, PTAL?

**Comment by pphaneuf** [comment]
While this PR lets us run `go mod tidy` without causing problems, it's unclear where these dependencies come from? Filed #793 to investigate this further.

**Pull request merged**
