### PR TITLE
Release v1.1.0

### LINKED ISSUE #613: Tag a new release?
The [most recent tagged release](https://github.com/google/certificate-transparency-go/releases/tag/v1.0.21) is from August 2018. Would you mind tagging a more recent release?

This is particularly relevant now that go modules are the norm, since go modules seems to strongly prefer tagged versions over arbitrary commits.

### PR DESCRIPTION
**Pull request by RJPercival**
Considered a minor version bump due to only features added.

Fixes #613.

### CODE REVIEW

**Comment by RJPercival** [comment]
I'm not convinced that the changelog is accurate.

**Comment by RJPercival** [comment]
The changelog is now fairly complete, although it doesn't mention Migrillian. I plan to complete this release on Monday.

**Comment by RJPercival** [comment]
If I release this as-is, it'll make some recent changes into breaking API changes so I'm going to instead rebase it on top of them first. That probably means more trawling through Git commit logs to complete the changelog though.

**Comment by AlCutter** [comment]
Are we still planning to release this one, or have plans changed?

**Comment by RJPercival** [comment]
I need to update the CHANGELOG further and bring a bunch of newer commits in.

**Comment by RJPercival** [comment]
Managed to confuse the CLA bot by targeting the PR against the v1.1 branch. I'm going to merge to master instead, then pull the v1.1 branch up to HEAD.

**Pull request merged**
