### PR TITLE
Don't allow the same private key to be used by more than one configured log

### PR DESCRIPTION
**Pull request by robstradling**
Each log/shard is expected to use a unique keypair.  This is [stated explicitly in RFC9162](https://www.rfc-editor.org/rfc/rfc9162#name-log-id:~:text=A%20log%20MUST%20NOT%20use%20the%20same%20keypair%20as%20any%20other%20log.), and although not clearly stated in RFC6962 (AFAICT) it is strongly implied.  If two logs share the same private key, then cryptographically speaking they should be considered as split views of the same log.

This PR ensures that no two logs in the CTFE configuration use the same private key.

h/t to @AlCutter for suggesting this check.

### Checklist

- [x] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [x] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by robstradling** [comment]
The CI build failure is expected, because the logs configured in ct_integration_test.cfg and ct_lifecycle_test.cfg all share the same keypair.  ;-)

**Comment by robstradling** [comment]
> The CI build failure is expected, because the logs configured in ct_integration_test.cfg and ct_lifecycle_test.cfg all share the same keypair. ;-)

Please post another `/gcbrun` comment.  I've generated unique key pairs for each of the integration test logs, so the CI build should now succeed.  Thanks.

**Comment by robstradling** [comment]
Another CI build failure:
`Step #6 - "etcd_with_coverage": /workspace/trillian/integration/ct_functions.sh: line 118: ./createtree: Text file busy`
Any idea how to resolve this?

**Comment by AlCutter** [comment]
> Another CI build failure: `Step #6 - "etcd_with_coverage": /workspace/trillian/integration/ct_functions.sh: line 118: ./createtree: Text file busy` Any idea how to resolve this?

Ah, that's a flake - just need to kick it again, hang on...

**Comment by robstradling** [comment]
Different error this time:
`Step #7 - "etcd_with_race": /workspace/trillian/integration/ct_functions.sh: line 118: ./createtree: No such file or directory`
Another kick needed?

**Comment by AlCutter** [comment]
Hmm, that's unexpected...

**Comment by robstradling** [comment]
Successful!

**Review by AlCutter — APPROVED** [review]

**Pull request merged**
