### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by RJPercival**
```shell
$ go get -u ./... github.com/mattn/go-sqlite3@v1.12.0 github.com/grpc-ecosystem/grpc-gateway@v1.11.2
$ go mod tidy
$ go generate ./...
```

Had to pin go-sqlite3 version because v2 fails due to the module name not matching the package name. Had to pin grpc-gateway version because of breaking change in patch release that makes newer versions incompatible with older generated code (such as that found in trillian v1.3.3).

Contributes to #614.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by Martin2112** [comment]
What brings in sqlite? I thought we removed it.

**Comment by RJPercival** [comment]
The Gossip code is using sqlite:
https://github.com/google/certificate-transparency-go/blob/ba4e6e2f6e40512709db1451c58ecb13b1bea13e/gossip/storage.go#L26

**Comment by RJPercival** [comment]
Do you think updates to go.mod ought to be mentioned in CHANGELOG.md? Arguably, it's pretty obvious when our go.mod changes so maybe not worth mentioning?

**Comment by Martin2112** [comment]
I think go.mod can look after itself, anyone interested can see the history and it will be pretty onerous trying to track changes manually.

**Pull request merged**
