### PR TITLE
Bump github.com/google/trillian to v1.5.2

### PR DESCRIPTION
**Pull request by phbnf**
- [x] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by roger2hk** [comment]
It looks like some indirect dependencies were missing. What command did you execute to bump the trillian version?

**Comment by phbnf** [comment]
`go get github.com/google/trillian`

**Comment by phbnf** [comment]
Bumped github.com/google/trillian to v1.5.2 and prometheus to v0.43.1 and ran go mod tidy

**Review by roger2hk — APPROVED** [review]

**Comment by phbnf** [comment]
Many thanks to @roger2hk for helping me getting the dependency updates right.

**Pull request merged**
