### PR TITLE
go mod tidy

### PR DESCRIPTION
**Pull request by pavelkalinnikov**

### CODE REVIEW

**Comment by Martin2112** [comment]
The travis failure looks spurious? Not seeing the button to rerun it.

**Comment by pavelkalinnikov** [comment]
Yeah, I can't see the restart button anymore. Do you?

**Review by Martin2112 — APPROVED** [review]
The build with etcd / race detection passed so I think this is ok.

**Comment by pphaneuf** [comment]
Not sure why it is failing (retried it a couple of times without success), but I did a `go mod tidy` in #756, and it's all passing, so might not be needed if I merge #756 in?

**Pull request closed without merging**
